### ISSUE TITLE
README should be more helpful

### ISSUE THREAD

**Issue by sur5r** [nnev/kzeen-wo-ist-die-pizza#1]
The current README makes it very hard to set this up. Would be nice if it could be improved.

**Comment by breunigs** [comment]
this sounds like a good first bug. Would you like to contribute @sur5r ?

**Comment by breunigs** [comment]
@sur5r, I have updated the README and added example configuration files. Can you take a look if this is sufficient to get it up and running? If not, please write down where you got stuck and I will add it to a more thorough guide.

**Comment by sur5r** [comment]
Looks pretty straightforward. I will test it in the next couple of days and report back.

**Comment by sur5r** [comment]
After setting it up on eris I think the setup instructions in the README are fine.
