### ISSUE TITLE
Pizza size in rendered PDF missing

### ISSUE THREAD

**Issue by joker234** [nnev/kzeen-wo-ist-die-pizza#5]
Currently, no size of a pizza is rendered in the downloadable PDF. It would be very helpful if one should not have to include this manually.

**Comment by breunigs** [comment]
compare website rendering:
https://github.com/nnev/kzeen-wo-ist-die-pizza/blob/master/app/views/order/_item_list.html.slim#L10-L12

to pdf rendering:
https://github.com/nnev/kzeen-wo-ist-die-pizza/blob/master/app/views/basket/fax.pdf.prawn#L59-L69
